name: Deployment

concurrency: production

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build project for production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VUE_APP_API_BASE_URL: 'http://47.119.197.247/a/r/api'
          envkey_VUE_APP_POOL: '4wKiSZGZiSRzvLpRPykPrCeHEYYSWUK6Rm3SRcixneJo'
          envkey_VUE_APP_ITEM_DATA_SIZE: '8 + 1 + 32 + 32 + 32 + 8 + 1 + 8;'
          envkey_VUE_APP_TOKEN_METADATA_PROGRAM_ID: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --ignore-engines

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
            
  deploy:
    name: Deployment via FTP
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: 47.119.197.247
          username: aiu
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/aiu/deploy/lm_web/
          
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_TITLE: Frontend code deployed
          
